baseURL = 'https://think-ke.github.io/playbook/'
languageCode = 'en-us'
title = "THiNK Playbook"

# Use Doks theme as Hugo module
[[module.imports]]
  path = "github.com/thuliteio/doks"

[params]
  description = "Technical documentation and guidelines for the Tech Innovators Network"
  author = "THiNK Team"
  github_repo = "https://github.com/think-ke/playbook"

# Menu configuration
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "Docs"
    url = "/docs/"
    weight = 20
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 30

[caches]
  [caches.images]
    dir = ':cacheDir/images'
