[[imports]]
path = "github.com/thuliteio/doks"

[[imports.mounts]]
source = "assets"
target = "assets"

[[imports.mounts]]
source = "static"
target = "static"

[[imports.mounts]]
source = "layouts"
target = "layouts"

[[imports.mounts]]
source = "archetypes"
target = "archetypes"

[[imports.mounts]]
source = "data"
target = "data"
